networks:
    tailrelay_devnet:
        name: tailrelay_devnet
        external: false

services:
    whoami:
        image: traefik/whoami
        container_name: whoami-test
        networks:
        - tailrelay_devnet

    tailrelay:
        container_name: tailrelay-test

        volumes:
            - ./tailscale/:/var/lib/tailscale
            - ./tailscale/Caddyfile:/etc/caddy/Caddyfile
        environment:
            - TS_HOSTNAME=tailrelay-dev
            - >-
                RELAY_LIST=8080:whoami-test:80,
                8081:whoami-test:80
        networks:
            - tailrelay_devnet
        image: sudocarlos/tailrelay:dev
        user: 1000:1000
