networks:
    tailrelay_devnet:
        name: tailrelay_devnet
        external: false

services:
    whoami:
        image: traefik/whoami
        container_name: whoami-test
        networks:
        - tailrelay_devnet

    tailrelay:
        image: sudocarlos/tailrelay:dev-local
        container_name: tailrelay-test
        volumes:
            - ./tailscale/:/var/lib/tailscale
            - ./tailscale/Caddyfile:/etc/caddy/Caddyfile
        environment:
            - TS_HOSTNAME=tailrelay-dev
        ports:
            - "8021:8021"  # Web UI
            - "2019:2019"  # Caddy Admin API
        networks:
            - tailrelay_devnet
